### ISSUE TITLE
Create an obvious  'fork me on github'  button for source code link

### ISSUE THREAD

**Issue by Tedko** [DimensionDev/Maskbook-Website#1]

**Comment by neruthes** [comment]
面白

**Comment by yisiliu** [comment]
> more easy

https://github.com/SujiTech/BetterLife/issues/5

**Comment by neruthes** [comment]
> > more easy
> 
> [SujiTech/BetterLife#5](https://github.com/SujiTech/BetterLife/issues/5)

233333333333
