### ISSUE TITLE
Add a blog site and add links to there

### ISSUE THREAD

**Issue by neruthes** [DimensionDev/Maskbook-Website#2]

**Comment by neruthes** [comment]
Let's determine the priority and ETA of this affair cc @yisiliu @Tedko

**Comment by Tedko** [comment]
before August

**Comment by Tedko** [comment]
@neruthes Let's say **go** for this version/design of events/news!

**Comment by Tedko** [comment]
@neruthes bring that live b4 August

**Comment by neruthes** [comment]
Let me add the link now.

**Comment by Tedko** [comment]
z👍👍

**Comment by Tedko** [comment]
Create an access point for https://dimension.im/ and https://tessercube.com as well @neruthes  Maybe the same News Link

**Comment by Tedko** [comment]
> Create an access point for https://dimension.im/ and https://tessercube.com as well @neruthes Maybe the same News Link

@neruthes
