### ISSUE TITLE
Multiple Client/Browser installation UI

### ISSUE THREAD

**Issue by Tedko** [DimensionDev/Maskbook-Website#4]

**Comment by Tedko** [comment]
Tested on Firefox, it's broken. Need to be fixed asap for BD purpose.

**Comment by neruthes** [comment]
Do you have any idea what URL you want to put here? I was advised that the user should be able to install with the generic CircleCI-compiled zip file.

**Comment by neruthes** [comment]
ping @tedko

**Comment by Tedko** [comment]
For now we have chrome store ver and Firefox ver as stable version.

For chrome/Brave etc maybe just go to that url;
For Firefox pls follow the design of 1Password.

No zip file. user wouldn’t able to use the zip file to install.

**Comment by Tedko** [comment]
For ‘follow 1Password’ — I think they just put the url of ‘install’ of
store page into their own ‘install button’
