### ISSUE TITLE
email subscribe button down

### ISSUE THREAD

**Issue by Tedko** [DimensionDev/Maskbook-Website#45]
![IMG_1F397C26EFE3-1](https://user-images.githubusercontent.com/6687437/100543602-fbb94c80-328b-11eb-8e25-f632b368ea4a.jpeg)

Need speedy fix

**Comment by zhouhanseng** [comment]
This button never worked.

Suji Yan <notifications@github.com> 于2020年11月29日周日 下午9:44写道：

**Comment by Tedko** [comment]
😂😂

**Comment by Tedko** [comment]
We got a mailchimp b4. I will give u these info later Monday

**Comment by zhouhanseng** [comment]
@Tedko okay
