### ISSUE TITLE
Time for Maskbook Mobile

### ISSUE THREAD

**Issue by Tedko** [DimensionDev/Maskbook-Website#6]
There're several things we need to update for Maskbook Mobile:

- Download Links etc. The better way is to have separate links/buttons (like MetaMask) instead of only one.
- the FAQ part on our website: 
> Can I use it on mobile devices?
> No for now. We cannot directly modify the the mobile apps directly without permissions. We are currently working on this and we are welcoming everything to contribute to this! Any help will be appreciated.

**Comment by neruthes** [comment]
Will re-evaluate these affairs when we are able to stabilize mobile versions.
