### ISSUE TITLE
Several Request 

### ISSUE THREAD

**Issue by Tedko** [DimensionDev/Maskbook-Website#7]
![Screen Shot 2019-12-21 at 04 28 32](https://user-images.githubusercontent.com/6687437/71287135-d436e000-23aa-11ea-8a7e-dc00822404b9.png)

- Replace the word 'Chrome' √

- Add a way to subscribe the email news

**Comment by neruthes** [comment]
Nice. Scheduled.

**Comment by Tedko** [comment]
Already replace the word Chrome.

Add subscribe email list by end of today

**Comment by neruthes** [comment]
done
